dist: trusty
sudo: false
matrix:
  include:
  - language: objective-c
    osx_image: xcode10.0
    before_script:
    - echo 'no need for ./.travisPre.sh'
    script:
    - cd tv
    - xcodebuild clean build -project tv.xcodeproj -scheme tv CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0' -quiet
    - xcodebuild test -project tv.xcodeproj -scheme tv -destination 'platform=iOS Simulator,name=iPhone X,OS=12.0'  -enableCodeCoverage  YES -quiet







